# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('roll', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('room', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Students',
            },
        ),
    ]
