# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 09:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='status',
        ),
    ]
