# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_students_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='is_deleted',
            field=models.SmallIntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0),
        ),
        migrations.AddField(
            model_name='students',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
