# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_students_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
