# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20170710_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='status',
        ),
    ]
