# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_students_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='is_deleted',
            new_name='status',
        ),
    ]
