# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20170710_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='status',
        ),
    ]
