# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_remove_students_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0),
        ),
    ]
