# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_students_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='profile',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
