# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20170712_1007'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='students',
            unique_together=set([('roll', 'token')]),
        ),
    ]
