# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-15 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_auto_20170925_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1),
        ),
    ]
