# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='eating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eating_on', models.DateField()),
                ('eating_item', django_mysql.models.JSONField(default=dict)),
                ('meals_taken', multiselectfield.db.fields.MultiSelectField(choices=[(0, b'Breakfast'), (1, b'Lunch'), (2, b'Snacks'), (3, b'Dinner')], default=[], max_length=7)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Students')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='eating',
            unique_together=set([('student', 'eating_on')]),
        ),
    ]
