# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentmeal', '0003_auto_20170706_1840'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eating',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='eating',
            name='student',
        ),
        migrations.DeleteModel(
            name='eating',
        ),
    ]
