# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-07 06:56
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('studentmeal', '0005_auto_20170706_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='eating',
            name='meals_opted',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, b'Breakfast'), (1, b'Lunch'), (2, b'Snacks'), (3, b'Dinner')], default=[], max_length=7),
        ),
    ]
