# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-15 17:19
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('studentmeal', '0009_auto_20171015_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealcount',
            name='is_veg_opted',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, b'Breakfast'), (1, b'Lunch'), (2, b'Snacks'), (3, b'Dinner')], default=[], max_length=7),
        ),
    ]
