# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-09 14:31
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='method',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, b'GET'), (1, b'POST'), (2, b'PUT'), (3, b'DELETE')], default=0, max_length=7),
        ),
    ]
