# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(default='perm4', to='staff.Permission'),
        ),
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.ForeignKey(default='staff4', on_delete=django.db.models.deletion.CASCADE, to='staff.Role'),
        ),
    ]
