# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20170630_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(to='staff.Permission'),
        ),
    ]
