# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-09 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_permission_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='api_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
