# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-09 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20170709_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='api_name',
            field=models.CharField(max_length=200),
        ),
    ]
