# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_remove_staff_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='is_deleted',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='is_deleted',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='is_deleted',
            new_name='status',
        ),
    ]
