# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_auto_20170710_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='profile',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
