# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100, unique=True)),
                ('vn', multiselectfield.db.fields.MultiSelectField(choices=[(b'VE', b'VEG'), (b'NV', b'NON-VEG')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField(choices=[(6, b'Sunday'), (0, b'Monday'), (1, b'Tuesday'), (2, b'Wednesday'), (3, b'Thursday'), (4, b'Friday'), (5, b'Saturday')], default=0)),
                ('time', models.PositiveIntegerField(choices=[(0, b'Breakfast'), (1, b'Lunch'), (2, b'Snacks'), (3, b'Dinner')], default=0)),
                ('menu_item', models.ManyToManyField(to='food.FoodItem')),
            ],
        ),
        migrations.AddField(
            model_name='fooditem',
            name='type_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.FoodType'),
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together=set([('day', 'time')]),
        ),
    ]
