# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20170703_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
