# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-09 19:40
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_fooditem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='vn',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(b'VE', b'VEG'), (b'NV', b'NON-VEG')], default=b'VE', max_length=5),
        ),
    ]
