# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20170710_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='is_deleted',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='foodtype',
            old_name='is_deleted',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='is_deleted',
            new_name='status',
        ),
    ]
